language: haskell

branches:
  only:
    - master

ghc:
    - ghc-8.4.3
    - ghc-8.6.3
    
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - alex-3.1.7
    - happy-1.19.5

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

