language: haskell

branches:
  only:
    - master

env:
 - CABALVER=head GHCVER=8.4.3

before_install:
  - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH

install:
  - travis_retry cabal update
  - cabal install

script:
  cabal test

