language: haskell

branches:
  only:
    - master

ghc:
    - 8.2.2
    - 8.4.3
    - 8.6.3
    
addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - alex-3.2.3
    - happy-1.19.8

before_install:
  - export PATH=/opt/alex/3.2.3/bin:/opt/happy/1.19.8/bin:$PATH

