language: haskell

branches:
  only:
    - master

ghc:
    - 8.2.2
    - 8.4.3
    - 8.6.3
    
addons:
  apt:
    sources:
    - hvr-ghc
    # packages:
    # - alex-3.1.7
    # - happy-1.19.5

# before_install:
  # - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH

