language: haskell

branches:
  only:
    - master

addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - cabal-install-2.0
    - ghc-8.4.3

before_install:
  - export PATH=/opt/ghc/8.4.3/bin:/opt/cabal/2.2/bin:$PATH

install:
  - travis_retry cabal update
  - cabal install

script:
  cabal test

